---
# tasks file for ansible-role-radarr

- name: Installing packages
  package:
     name: "{{ item }}"
     state: present
  with_items:
     - mediainfo

- name: Add user "{{ radarr_user }}"
  user:
    name: "{{ radarr_user }}"

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ radarr_user }}"
    group: "{{ radarr_group }}"
  with_items:
     - "/home/{{ radarr_user }}/.config/Radarr/"
     - /opt/Radarr

- name: Ensures /home/{{ radarr_user }}/.config/Radarr/ dir exists
  file: path=/home/{{ radarr_user }}/.config/Radarr/ state=directory

- name: Installing Radarr
  unarchive:
    src: "{{ radarr_source }}"
    dest: /opt/
    remote_src: yes
    creates: /opt/Radarr/Radarr
  become: yes
  become_user: "{{ radarr_user }}"

- name: Configuring Autostart
  template:
    src: templates/radarr.service.j2
    dest: /etc/systemd/system/radarr.service


- name: Configuring Radarr config.xml
  template:
    src: templates/config.xml.j2
    dest: /home/{{ radarr_user }}/.config/Radarr/config.xml
  become: yes
  become_user: "{{ radarr_user }}"

- name: Enable Service
  systemd:
    name: radarr
    enabled: yes
    masked: no

- name: Enable Service
  ansible.builtin.systemd:
    name: radarr
    state: started
    enabled: yes
    daemon_reload: yes

- name: Start Radarr
  systemd: state=started name=radarr